### ISSUE TITLE
Unable to load dependency: plugins/helper/libraries/slf4j-api-1.7.30.jar initializing helper-sql v1.3.2 (Is it up to date?)

### ISSUE THREAD

**Issue by cloakfox** [lucko/helper#101]
Hey, I was testing java 16 and noticed this helper-sql error on bootup. Im not sure if it's harmful because all our plugins that use helper-sql seem to work fine.

https://gist.github.com/cloakfox/fe749611222081c5b488d1d6ea2b6b12

The server runs git-Airplane-"a13c511" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
(a fork of tuinity)

**Comment by cloakfox** [comment]
Still same issue
https://gist.github.com/cloakfox/140699dc051ef1b31759a0b239174a47

**Comment by lucko** [comment]
There ya go :)
