### ISSUE TITLE
Extending the ExtendedJavaPlugin on 1.17 Startup Error

### ISSUE THREAD

**Issue by darbyjack** [lucko/helper#103]
Hi there,

Currently working on upgrading some of the projects that use Helper to 1.17. With 1.17, we also know that it is a Java 16 requirement. When changing to development on strict Java 16, there seems to be some reflection issues in Helper. Here's a copy of a stacktrace.

https://paste.helpch.at/iridajohuy.cpp

**Comment by darbyjack** [comment]
Ignore this. I just realized that the version was never bumped on the Java 16 fix so it never actually seems to have deployed. I ended up switching to have it compile off of Jitpack + Commit hash.

**Comment by lucko** [comment]
I've bumped the version and deployed :)

**Comment by darbyjack** [comment]
Not sure if this was in the previous version but after deploy I seem to be getting this error on shutdown in another project. https://paste.gg/p/anonymous/2174c785eee14760beffbb9046c310d3
