### ISSUE TITLE
Hocon Configuration

### ISSUE THREAD

**Issue by XuPuPG** [lucko/helper#108]
It is completely incomprehensible how to use your api.
How do I serialize/deserialize a class? Class -> Hcon -> Class
How to work with the config node tree?
How to add a node? All I get when I try to directly add a node to the map is
![image](https://user-images.githubusercontent.com/11676369/129132810-5af621ef-5315-4bda-894d-1462734cc65d.png)

**Comment by Baricaade** [comment]
If I'm not mistaken helper uses Sponge's Configurate (https://github.com/SpongePowered/Configurate) for configuration.

And if you don't like the API... don't use it? I see absolutely no need to post an issue about how you can't understand a certain API when I can almost guarantee that there are probably alternatives out there that may even suit your needs better.
