### ISSUE TITLE
Missing api-version in add-on modules

### ISSUE THREAD

**Issue by TheLuca98** [lucko/helper#124]
The main helper.jar correctly specifies `api-version: 1.13` in the plugin.yml, but all the other modules are missing that property, forcing the server to load them in legacy mode unnecessarily.

**Comment by lucko** [comment]
Should be an easy PR? :)

**Comment by TheLuca98** [comment]
I was hoping you wouldn't say that :p

#125

**Comment by lucko** [comment]
Thank youuuu!
