### ISSUE TITLE
Jenkins - package me.lucko.scriptcontroller.environment.settings does not exist

### ISSUE THREAD

**Issue by andrewkm** [lucko/helper#22]
Full console output:
https://gist.githubusercontent.com/andrewkm/b7ad1d932a5aa1f211319e89dff840ae/raw/99fd7409fa689023564566de186efee5ab2539ff/gistfile1.txt

We're trying to do some Helper work for 1.13.2 as it's the only thing left for one of our **entire gamemodes**, that heavily depends on it, to function. My last roadblock is the jenkins issue above, which you've stated you experience as well.

It would be amazing if you could fix this some time for us <3

**Comment by lucko** [comment]
9ca567d3336e1a4df49f220e313f61c381e7b94d
