### ISSUE TITLE
Update to Minecraft 1.14

### ISSUE THREAD

**Issue by Leonardo-DGS** [lucko/helper#28]
Helper doesn't works for some things with 1.14, it needs updating

**Comment by InfinityZ25** [comment]
Furthermore: Helper's scoreboard doesn't work in 1.14.

Also, is there an ETA for:
Bossbar
Hologram
Sign Prompt
BungeeCord
Profiles
Npc
?

**Comment by lucko** [comment]
No ETA, PRs that add support for 1.14 whilst maintaining support for previous versions would be appreciated.

I believe the scoreboard is the only problematic area.

**Comment by InfinityZ25** [comment]
I guess i coudl write that

**Comment by NickAcPT** [comment]
I'm also running to this problem with Individual Holograms.

**Comment by lucko** [comment]
Still no ETA, sorry. PRs still welcome.

**Comment by Leonardo-DGS** [comment]
@lucko can you accept my PR?

**Comment by lucko** [comment]
Apologies, just left a comment. :)
