### ISSUE TITLE
Disable tab-completion for players that doesn't have a command permission

### ISSUE THREAD

**Issue by Leonardo-DGS** [lucko/helper#29]
If you register a command with a permission with Helper, it tab-completes even for players that doesn't have the permission, to fix this, when Helper registers a command, it should use default Bukkit Command#setPermission() and Command#setPermissionMessage().

**Comment by lucko** [comment]
PR pls?

**Comment by Leonardo-DGS** [comment]
> PR pls?

@lucko #30
