### ISSUE TITLE
BungeeCord module and different structure

### ISSUE THREAD

**Issue by Leonardo-DGS** [lucko/helper#33]
It would be useful to have a BungeeCord module `helper-bungee`, and have a module with all code that does not rely on any server code like `helper-common`, and a module `helper-bukkit`.

**Comment by FerusGrim** [comment]
I don't disagree, but such a conversion would have to very carefully ensure backward compatibility. I'm fairly certain this would require a lot of time and effort, and would likely be completed in a PR format.

Additionally, @lucko would have to decide if non-Bukkit-specific functionality is even within the scope of helper.

**Comment by lucko** [comment]
For this sort of thing, I'm less worried about backwards compatibility and more that the code is nice - it would just be a new major version, `6.0.0`.

I agree it would be nice.

However, I personally have no need for such a library at the moment, so don't really see myself programming the necessary changes myself.

Sure if someone from the community wants to maintain this, then awesome - just not something I want to do myself right now. :)
