### ISSUE TITLE
PacketScoreboard index out of bounds

### ISSUE THREAD

**Issue by Ean244** [lucko/helper#37]
I've encountered an error when using PacketScoreboardProvider in my code:
`Scoreboard scoreboard = Services.load(PacketScoreboardProvider.class).getScoreboard();`

It caused an error when I joined the server:
https://hastebin.com/alijexifil.md

Maybe some method that was used is modified in future nms versions? I'm using 1.14.4 latest stable version

**Comment by FerusGrim** [comment]
Could you provide both your Helper and your ProtocolLib version numbers?

**Comment by Ean244** [comment]
Helper: 5.5.0
Protocollib: 4.4.0

**Comment by FerusGrim** [comment]
Any chance you could attempt to replicate this bug using a ProtocolLib version that supports 1.14?

**Comment by NickAcPT** [comment]
I also have this problem and I know that ProtocoLib isn't the problem here.
The problem, afaik, is that the some packet structure was changed in-between versions of the game. I feel like the best way to do it is to use the packet wrappers from protocollib

**Comment by lucko** [comment]
Yep, the scoreboard just needed to be updated to 1.13+

b6d8dabc64cc114ef9c6129d80c0e9a024fc52c5
