### ISSUE TITLE
IndexOutOfBounds when clicking on Paginated gui's buttons on extremities

### ISSUE THREAD

**Issue by JamieSinn** [lucko/helper#5]
https://pastebin.com/pMftVE1Z is spammed in console each time a GUI that is paginated has the forward/back buttons pressed when you're on the limits of the pages (ie, pressing back on page 1, pressing next on the last page.)

- This is the location of the forward/back buttons
https://i.imgur.com/IFj0kRF.png

- If I click here, on the last page, it throws that error. (Same with the back on the first page.)
https://i.imgur.com/3d6v0pL.png

Repeatedly clicking on it allows the current page to be past the index, requiring to hit the back buttons multiple times to return to valid pages.
https://pastebin.com/aHGAPHMg

**Comment by lucko** [comment]
Thanks for reporting it :)

**Comment by andrewkm** [comment]
This is still not fixed. I continue to get errors with this @lucko 
https://pastebin.com/raw/WAxAsSdZ

Please check it out <3

**Comment by andrewkm** [comment]
Confirmed fixed. Many thanks!
