### ISSUE TITLE
Switch to different Javascript engine

### ISSUE THREAD

**Issue by Andre601** [lucko/helper#65]
Considering that Nashorn is deprecated now with Java 11 and may get removed in the future would I suggest to switch to a different engine.

**Comment by FeaturedSpace** [comment]
And what would you advise? There aren't many competitors from what I know.

**Comment by jwpjr-dev** [comment]
@FeaturedSpace GraalVM.

**Comment by mdcfe** [comment]
Related: https://github.com/graalvm/graaljs/blob/master/docs/user/RunOnJDK.md

**Comment by Ristovski** [comment]
Nashorn has been removed as of Java 15 - https://openjdk.java.net/jeps/372.
This makes running `helper-js` on 1.17 (which requires Java 16) impossible.
