### ISSUE TITLE
Scoreboards not working

### ISSUE THREAD

**Issue by TKDKid1000** [lucko/helper#89]
I am trying to use helper for the sidebar scoreboards. I added helper as a dependency in maven and used this:
```xml
<dependency>
        <groupId>me.lucko</groupId>
        <artifactId>helper</artifactId>
        <version>5.6.5</version>
        <scope>provided</scope>
    </dependency>
```
I also added the helper plugin to my server. Downloaded from https://ci.lucko.me/job/helper/lastSuccessfulBuild/artifact/helper/target/helper.jar. I only used the base helper as that is all I need. I also added helper as a depend in my plugin.yml, but even then I still get this error https://bytebin.lucko.me/bQimttSvmd
My server verion:
`This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
Does anyone know why, or is this potentially a helper bug.

**Comment by Baricaade** [comment]
You'll need to install ProtocolLib in order for it to work, as helper's scoreboard library depends on that.

**Comment by TKDKid1000** [comment]
> You'll need to install ProtocolLib in order for it to work, as helper's scoreboard library depends on that.

Oh! I never realized that. I'm assuming I can just the spigotmc.org protocol lib?

**Comment by Baricaade** [comment]
> > You'll need to install ProtocolLib in order for it to work, as helper's scoreboard library depends on that.
> 
> Oh! I never realized that. I'm assuming I can just the spigotmc.org protocol lib?

Yes, it should just be a standalone plugin you can install afaik.
