### ISSUE TITLE
PacketHologram can not click

### ISSUE THREAD

**Issue by huanmeng-qwq** [lucko/helper#95]
PacketHologram can not click
can not run clickCallback

`
this.hologram=this.hologramFactory.newHologram(Position.of(xx)), lineBuilder.build());

hologram.setClickCallback((p) -> {
  update();
});
hologram.spawn();
hologram.addViewer(player);
`

ProtocolLib: 4.5.1
Minecraft Client Version: 1.8.9
Server Version: 1.8.8 Spigot
helper plugin version: latest

**Comment by huanmeng-qwq** [comment]
@lucko

**Comment by lucko** [comment]
df170974b83073d48bc9dd2adf8aceb3b8331443
