### ISSUE TITLE
Redis update

### ISSUE THREAD

**Issue by AoElite** [lucko/helper#99]
Could redis be updated to at least 2.10.1?

**Comment by PepejHa4ker** [comment]
Create Pull Request and update it yourself :)

**Comment by AoElite** [comment]
Already did update it myself but I don't want to create a pull request so have fun

**Comment by kaxon-dev** [comment]
Is a pull request necessary to update one line in a pom.xml file?

**Comment by lucko** [comment]
It is already 2.10.1
